# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This is a Kconfig fragment which can be used to enable debug-related options
# in the application. See the README for more details.

# compiler
CONFIG_DEBUG_OPTIMIZATIONS=y

# logging
CONFIG_LOG=y
CONFIG_APP_LOG_LEVEL_DBG=y

CONFIG_MCUMGR_TRANSPORT_LOG_LEVEL_DBG=y
CONFIG_MCUMGR_GRP_IMG_LOG_LEVEL_DBG=y

CONFIG_VCU_PORTS_MOCK=y

CONFIG_SHELL=y

# telnet config
CONFIG_NET_TCP=y
CONFIG_NET_SHELL=y
CONFIG_SHELL_BACKEND_TELNET=y

CONFIG_STATIC_VCU_DEV=n
